# Generated by Django 4.1.7 on 2023-02-27 13:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('TOP', 'TOP'), ('NEW', 'NEW'), ('SALE', 'SALE')], max_length=20)),
                ('stock', models.JSONField(default=main.models.Product.availability_stock_default)),
                ('way', models.JSONField(default=main.models.Product.availability_way_default)),
                ('remote', models.JSONField(default=main.models.Product.availability_remote_default)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('carton', models.IntegerField(blank=True, null=True)),
                ('rrc', models.IntegerField(blank=True, null=True)),
                ('weight', models.CharField(choices=[('10', '10'), ('100', '100'), ('1000', '1000'), ('10000', '10000')], max_length=20)),
                ('id_product', models.ManyToManyField(to='main.product')),
            ],
            options={
                'verbose_name': 'Список продуктов',
                'verbose_name_plural': 'Список продуктов',
            },
        ),
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('id_product_list', models.ManyToManyField(to='main.productlist')),
            ],
            options={
                'verbose_name': 'Основной продукт',
                'verbose_name_plural': 'Основной продукт',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=200)),
                ('id_main_product', models.ManyToManyField(to='main.mainproduct')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
    ]
