# Generated by Django 4.1.7 on 2023-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Банеры',
                'verbose_name_plural': 'Банеры',
            },
        ),
    ]
