# Generated by Django 4.1.7 on 2023-03-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_delete_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CHECK', 'Расчетный счет')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='way_get',
            field=models.CharField(choices=[('DELIVERY', 'Доставка'), ('PICKUP', 'Савывоз')], max_length=100),
        ),
    ]
